### ISSUE TITLE
Crashing when accessing options menu in 0.9.0 16-11-19

### ISSUE THREAD

**Issue by MaridaConnoisseur** [sudasana/armcom2#11]
1. Open armcom2.exe
2. Press O to access options menu
Happens on fresh install
Windows 10 1903/Python 3.8.0 64-bit (also occurs under 3.7.3 64-bit)

**Comment by sudasana** [comment]
This is due to an old armcom2.cfg file in the /data folder. If you delete this file, the game will generate a new one and it won't be missing the required data.

**Comment by sudasana** [comment]
I've updated the development build so that it doesn't have a copy of armcom2.cfg included, should be fixed from now on. Thanks for the report!
