### ISSUE TITLE
Crash on air support

### ISSUE THREAD

**Issue by AdmiralKew** [sudasana/armcom2#13]
I was playing a US campaign with the M4A3 (76)
The mission was to advance.

I went into a combat tile and was about to fire on a truck when the game told me that my side was launching air support.

I crashed immediately.
[ArmCom2 save.zip](https://github.com/sudasana/armcom2/files/3958160/ArmCom2.save.zip)

**Comment by sudasana** [comment]
Thanks for the report - it was a case of a couple function calls not being updated. Fixed in Alpha 9.2: https://github.com/sudasana/armcom2/commit/3e1a041b2ee010d8ac35e437b6ec4ed934ffcd5d
