### ISSUE TITLE
anti-tank gun 105 K/13 protected from Close Combat ;)

### ISSUE THREAD

**Issue by zaimoni** [sudasana/armcom2#14]
[CloseCombat.105K13.Crash.zip](https://github.com/sudasana/armcom2/files/4206810/CloseCombat.105K13.Crash.zip)

1) Press W

2) "Defending units engage in defensive fire"

3) crash to desktop

This is for the Alpha 13 downloaded Feb 9 2020.

**Comment by sudasana** [comment]
Fixed in most recent update: https://github.com/sudasana/armcom2/commit/bf6af4eeb6754d15acb93e84632049a61cfb6343
