### ISSUE TITLE
Crash on close combat

### ISSUE THREAD

**Issue by Doubleumc** [sudasana/armcom2#16]
ArmCom2 1.0.4, Windows 10
Riflemen and Opel immediately in front of tank. Upon starting assault, defending riflemen is destroyed, then game crashes. Crash is consistent and repeatable. Save file(s) attached.
[savegame.zip](https://github.com/sudasana/armcom2/files/4341487/savegame.zip)

**Comment by Doubleumc** [comment]
Additional crash, similar situation. HMG and Opel immediately in front of tank. Start assault, HMG destroyed, then game crashes.
Not consistent. Second attempt Opel was destroyed first, then HMG. No crash.
[savegame.zip](https://github.com/sudasana/armcom2/files/4341530/savegame.zip)

**Comment by sudasana** [comment]
Thanks for finding this! It had been reported before I was never able to isolate it. Default close combat firepower had been set to 0, which led to a division by zero crash when non-combat units like trucks were involved. Fixed in 1.0.5.
