### ISSUE TITLE
Day not changing

### ISSUE THREAD

**Issue by Edward-O** [sudasana/armcom2#17]
So I was playing the Canadian campaign, and I figured it would be longer since it's 3 and a half years instead of just a few months... but I still figured it would end at most only with 3x to 4x the points that France and Poland ended with -  So I slowed down a little and noticed that every new day was starting on October 22 1944 - I wish I had checked when this had started, but.... my guess would be that I played through October 22 a crazy number of times between 30 and 40 battles.

**Comment by sudasana** [comment]
The campaign weeks were not entered properly in the Canada's Best campaign file, which led to two October 22nd days being generated for your campaign. Fixed here: https://github.com/sudasana/armcom2/commit/26c30299349f228ed839981d8658ebfede8801e5
