### ISSUE TITLE
Date issues in the Liberation campaign.

### ISSUE THREAD

**Issue by YARDRL** [sudasana/armcom2#18]
Liberation Campaign of the Red Army never transitions from September to October. Instead, it keeps adding days to September, eventually ending on September 36.

![изображение](https://user-images.githubusercontent.com/62474429/77229595-e68a0b00-6b9f-11ea-8638-20490e9451f1.png)

![изображение](https://user-images.githubusercontent.com/62474429/77229651-23560200-6ba0-11ea-8d2a-4afe40297c56.png)

**Comment by Edward-O** [comment]
I had this too.

**Comment by sudasana** [comment]
Thanks for this - the campaign file had a final week that started on September 31st, which doesn't exist! Fixed it https://github.com/sudasana/armcom2/commit/cdf5bcca78f49c2cfffd3715f623ff13f48b537f
