### ISSUE TITLE
Clarify the rules around Close Combat.

### ISSUE THREAD

**Issue by YARDRL** [sudasana/armcom2#20]
Currently, the player is given a highly detailed chance breakdown whenever they fire either their tank's main gun or one of its MGs at the enemy, which is great.

However, nothing like this exists for close combat. This is in spite of the fact that failing in close combat has **far** more drastic consequences than failing at range; the latter will at most waste some ammo, while a failure in close combat can straight-up destroy your tank and end your campaign, either immediately, or in a few days, as the wounded commander gets discharged.

Thus, I am asking for a screen that will show percentage breakdown before initiating close combat, just like there is one when you are about to shoot at something. It is currently complete guesswork as to whether or not your tank is ever safe from being suddenly destroyed in such a manner (the manual currently does not even acknowledge that as a possible outcome.)

 I first assumed that this could only happen when assaulting the artillery, but then the same thing occurred when I drove at Riflemen. I thought that was because of their AT Rifle, but then assaulting an HMG Team led to a destroyed tank again. My best guess is currently that the state of the tile where you are performing the assault is what makes the difference, but again, it's just a guess. Right now, the safest way to play is to completely avoid any and all assaults because of this uncertainty.

**Comment by sudasana** [comment]
The close combat system right now is very much a rough placeholder for a future, better system that will incorporate a very small "minigame." I mainly included it so that if you're just left with a single infantry squad at the end of a battle, you can assault it and take it out quickly. Tanks are not really meant to engage in close assault, especially without infantry support, so initiating close combat is always going to be a risky prospect. I think for now, like you say, it's best avoided unless your target is pinned and you have overwhelming firepower.

I'll write up a brief outline of the system as it stands in the [manual](https://github.com/sudasana/armcom2/blob/master/MANUAL.md) though.

**Comment by YARDRL** [comment]
Well, it was actually the HMG Teams that baffled me the most. Infantry squads do possess AP Rifles and can also deploy grenades (or, hell, if it's a Finnish campaign and such, Molotov cocktails) up close. HMG Teams have nothing but their gun that's useless against frontal armor of all but the lightest tanks.

I can also get the idea that your tank can end up destroyed if you are assaulting a Fortified tile due to the fortifications collapsing on it or something. On some of the other rough tiles (i.e. Dug-In, Marsh), there should probably be an extra chance of your tank becoming immobilized while assaulting and thus letting the defenders get a free hit at high accuracy (extremely dangerous against artillery), but NOT a straight-up auto-destroy chance.

Did not consider Pinning affecting the close combat success rates, but yeah, it makes sense.

I honestly have a lot of thoughts about both the individual unit categories and the underlying mechanics, and I am unsure whether the best approach is to create a separate issue for each one, or a larger issue that would cover several. (Or straight-up move the discussion to somewhere like Discord.)

**Comment by sudasana** [comment]
Maybe open up a new issue for general discussion of unit categories and game mechanics, and we can discuss it there.

**Comment by YARDRL** [comment]
Will do!

**Comment by sudasana** [comment]
Close combat has now been completely revised - the player gets an "Overrun" attack which is basically a close-range attack on infantry or guns, and infantry have their own Close Combat weapons to use against the player and allies. I had starting putting together a close combat mini-game but it quickly became clear that it was going to detract from the focus of the game, so I abandoned that idea. Will continue to refine overrun and close combat attacks as I move forward.
