### ISSUE TITLE
T-28 main gun incapable of Maintaining Fire?

### ISSUE THREAD

**Issue by YARDRL** [sudasana/armcom2#21]
In both of the currently available Soviet campaigns, T-28 has not been able to maintain fire with its 76mm weapon even once, and even after the Loader was given the Fast Hands trait and had multiple points added into Knowledge. 

In contrast, the main gun of the Matilda tank is able to fire 3-4 times a turn even without any upgrades; the main weapon of the Sherman Firefly can also pull off multiple shots a turn from the first days of the campaign, even though it has the same caliber as the T-28's weapon, and its extra length should, if anything, make loading more difficult.

**Comment by sudasana** [comment]
I've added a very small chance of RoF for the T-28's main gun, so at least this can be improved by crew skills. https://github.com/sudasana/armcom2/commit/065a5b9acc129875754f6d4f1876f598f4a266fb
