### ISSUE TITLE
Ammo Loading Screen Broken

### ISSUE THREAD

**Issue by BlakeBi** [sudasana/armcom2#22]
Version 1.0.6 from main download link

On starting a new campaign:
Game will not progress if during the ammo loading screen you move any amount of ammo into the tank. Moving ammo works, but pressing enter to proceed will not work if you adjust the ammo load.

It works fine if you have a tank with one ammo type and it skips the screen. You can also move past the screen without loading any ammo at all and acknowledging the warning.

Have tested it with multiple tanks on multiple campaigns, same result each time.

Not sure it's it's related, but if you try to move ammo on the ammo load screen too fast this error pops up:

ERROR: could not play sound: shell_move_10
b'That operation is not supported'

**Comment by sudasana** [comment]
Fixed now: https://github.com/sudasana/armcom2/commit/6e4ed869e8ebbb99827af8c94a13e39ff37db9bd

You can re-download from the 1.0.6 download link and this bug will be fixed.

Not sure what's happening with the sound error, haven't been able to replicate it here, but will investigate further.

**Comment by sudasana** [comment]
Thanks for reporting this, by the way. It was a stupid coding mistake that I should have caught earlier. 😅
