### ISSUE TITLE
VP values after moving to a new map screen

### ISSUE THREAD

**Issue by Edward-O** [sudasana/armcom2#24]
When you move to a new map screen in (Battle, Advance, and Spearhead), only the bottom row of tiles will have VPs (except in spearhead) everything else will be worth 0, UNTIL you have moved one hex- then the game will update and award VPs again -

I've found that the "one move" can be EITHER a sidestep into a bottom row tile, or biting the bullet and taking a move into one of the 0 point hexes in the second row. 

I don't usually lose out many VP because of this because of the sidestep work around, but it is easily repeatable and happens to multiple nations (although the mission type is rare for eg Poland)

**Comment by sudasana** [comment]
Thanks for this! Fixed by adding in an extra step to re-calculate capture VP values after moving into a new map: https://github.com/sudasana/armcom2/commit/6afbfbd49329575a022ebf44b346ea27e3027404
Will update the downloadable build right now
