### ISSUE TITLE
Ambush at start of battle seems to happen more frequently

### ISSUE THREAD

**Issue by Edward-O** [sudasana/armcom2#27]
I am not sure how this works exactly even on the old patches. Does it only check the Commander's Perception skill or does it check some kind of average of everyone's Perception? I am not sure how strong the Eagle Eye skill is either, but if the commander is under 5 perception it doesn't seem to help much.

**Comment by sudasana** [comment]
The two things that have the biggest effect on this are whether one of your crew has the "Enemy Spotted!" skill, and if 1+ crewmen have their hatches open when the battle starts. Not having at least one crewman with an open hatch doubles the odds of being ambushed.

**Comment by sudasana** [comment]
It's a pretty simple check right now though, I'll see about making it a little more nuanced, take into account weather conditions, etc.

**Comment by sudasana** [comment]
I've made this change now: https://github.com/sudasana/armcom2/commit/7def273090c4288c18ba20419c5d9873b66811b8
