### ISSUE TITLE
Need a check to prevent using Advancing Fire and Call arty support when using the Wait command

### ISSUE THREAD

**Issue by Edward-O** [sudasana/armcom2#28]
Normally, these won't appear on the strategic map until you have picked the direction of an enemy hex, but if you pick the direction of the enemy hex first, and then choose to wait anyway, they seem to still apply.

**Comment by sudasana** [comment]
Good find, I'll make the change.

**Comment by sudasana** [comment]
Ok I checked the code and if you wait in place, neither Advancing Fire nor arty/air support are called in. Your options remain active, but no HE rounds or support levels are used, they are only activated if you move. If you wait in place and your hex zone is captured by enemy forces, then a Scenario is triggered, but in that scenario you don't get the benefit of either Advancing Fire or arty/air support.

**Comment by Edward-O** [comment]
Are you sure? Because I had the enemies being pinned on turn 1 multiple times when I tried this.

The artillery I guess can happen as a random event at the start of some battles so that mght have been misleading me due to coincidence.

**Comment by sudasana** [comment]
Ah you're right! I'll fix that in a future update.

**Comment by sudasana** [comment]
This is fixed now: https://github.com/sudasana/armcom2/commit/9d719b69f07ead5c11e690b651cc2efef77072ca
, will upload a build for 3.0.2 soon
