### ISSUE TITLE
Line of sight blocked units still use normal spotting

### ISSUE THREAD

**Issue by Edward-O** [sudasana/armcom2#29]
Line of sight blocked units can spot and be spotted the same as normal units - however shooting them is correctly blocked. In the case of Troop Transport trucks their unload AI also seems to be active before spotting the player tank (although I suppose this is fine)

**Comment by Edward-O** [comment]
I'm starting to notice that Ally tanks can still shoot machineguns and main guns at Line of sight blocked units.

Amending this to add that I've had enemy (LOS) tanks kill my ally tanks, but still never target me.

**Comment by sudasana** [comment]
So this isn't a bug but it is poor communication on my part - your squadmates have their own LoS links to enemy units, so an enemy that is blocked to you may be visible to a squadmate. Once an enemy is spotted, however, all allied units know about it. So you may receive radio reports of an enemy unit in a given location, even though you can't see them from your tank.

I'll add some extra language in the "spotted" notification like "An allied unit reports:"
