### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Stew-rt** [sudasana/armcom2#4]
Would you be willing to accept a pull request upgrading the code to use python 3?

**Comment by sudasana** [comment]
Actually I was planning on upgrading the master branch to Python 3! I just need to confirm that all the packages I use are compatible, but if everything looks good then I will upgrade.

**Comment by Stew-rt** [comment]
2to3 works fine on armcom2.py - the only bits I found that didn't automatically convert where xp_loader.py and libtcod.py. where I had to manually change some ".encode.hex" parts to "binascii.b2a_hex(some_var)"

**Comment by sudasana** [comment]
Excellent - both of those packages allow modifications so that should not be a problem either.

**Comment by sudasana** [comment]
I did a quick initial conversion to run under Python 3, it's far from finished but it will boot to the main menu now. There's still some work to be done in how strings are handled (crew names are messed up) and in switching to different ways of accessing dictionary keys.

**Comment by sudasana** [comment]
I've been running the current version on Python 3.6.6 (in order to maintain compatibility with PyInstaller) and have not encountered any more crashes. There's probably a few leftover incompatible functions still to discover but I will fix them as I find them.

**Comment by sudasana** [comment]
Has been running well on Python 3 for some time now.
