### ISSUE TITLE
Bug crash in setting crewman action on MoveForward

### ISSUE THREAD

**Issue by Stew-rt** [sudasana/armcom2#6]
the function MoveForward calls an undeclared function `GetStat('reverse_driver')` on line 5952 of armcom2.py

This would result in a crash.

this should *probably* be something like `self.GetStat('reverse_driver')`

**Comment by sudasana** [comment]
Fixed!

https://github.com/sudasana/armcom2/commit/b3511bda08cc4d022971d64adb08ac167ffd5765
