### ISSUE TITLE
missing libtcod.so

### ISSUE THREAD

**Issue by brianpath999** [sudasana/armcom2#8]
I seem to be missing this. I see that there's the .dlls. But, libtcod clearly wants libtcod.so. How can I get this?

**Comment by brianpath999** [comment]
alright I built it myself but now I get the error: undefined symbol: TCOD_console_get_foreground_color_image

**Comment by sudasana** [comment]
I suspect that this is an issue with libtcod rather than the armcom2 code - I've never run it on Linux though so I'm not 100% certain.

https://bitbucket.org/libtcod/libtcod/src/default/

**Comment by Zireael07** [comment]
@brianpath999: Looks like you got a different version of Libtcod than the one armcom2 uses?

**Comment by brianpath999** [comment]
hm, I've tried 2 versions of libtcod. Building the so from the latest on that default branch, and the version built in the linux fork of ArmCom1. Same issue for either. I suppose I could try another version, but I'd be interested to know what version of the library other people who have run ArmCom2 on linux before use.

**Comment by brianpath999** [comment]
Alright, I've tried building every version of libtcod that will build, and I can't get any to work.

**Comment by brianpath999** [comment]
I figured out the source of the issue. The libtcodpy-local file is targeting a way outdated copy of libtcod, and causing problems. The file isn't really needed anymore in the new version of libtcodpy, but armcom2 uses it so closely I think that it might be difficult to remove. I'll try though and see.

**Comment by brianpath999** [comment]
I have gotten the game working. If you'd like, I can make a branch for it in this repo.

**Comment by Zireael07** [comment]
@brianpath999: Are you familiar with how forking works on GitHub? It's not just 'making a branch in this repo', as 'this repo' is RevSudasana's.

**Comment by brianpath999** [comment]
sorry, I meant a fork. I know how forking works.

**Comment by brianpath999** [comment]
linux fork is set https://github.com/brianpath999/armcom2

**Comment by brianpath999** [comment]
I also updated the ArmCom1 linux fork to 1.04: https://github.com/brianpath999/ArmouredCommanderLinux
